# Generated by Django 3.1.5 on 2021-01-11 00:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='essay',
            field=models.OneToOneField(help_text='The essay being edited as part of the feedback request. For simplicity, we assume that a feedback request consists of only one essay.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='project.essay'),
        ),
    ]
