# Generated by Django 3.1.5 on 2021-07-21 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210721_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='assigned_editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_feedback_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
